# Asport Server Quick-start Configuration

# Listen address.
# Format: <ip>:<port>
# Note: If you want to listen on localhost, use "[::1]:443".
# Port 443 may be blocked by some ISPs. You can use other ports such as 4443.
server = "[::]:443"

# Congestion control algorithm.
# Default: "cubic"
# Options: "cubic", "reno", "bbr"
# Note: BBR may incrase transmission rate.
congestion_control = "bbr"

# ALPN for QUIC handshake.
# Default: ["asport"]
# Format: ["<protocol-1>", "<protocol-2>", ...]
# Note: Set it to ["h3"] if you want to bypass some DPI. And you should also change the client's ALPN to ["h3"].
alpn = ["h3"]

# Authentication failed reply.
# Default: true
# Note: Set it to true for hiding your server from probing.
authentication_failed_reply = false

# Log level.
# Default: "warn"
# Options: "trace", "debug", "info", "warn", "error", "off"
# Note: If you want sumbit a bug report, you should set this to "trace" or "debug"
log_level = "warn"

# Security configuration.
[security]
# Security layer for QUIC.
# Default: "tls"
# Options: "tls", "noise"
# Note: "noise" is not recommended for production use.
type = "tls"

# TLS configuration for security layer.
[security.tls]
# Path to the certificate file or the certificate in PEM format.
# Note: DER and PEM format are supported for file.
# You can use acme.sh to get a free certificate.
# See also: https://acme.sh
certificate = "path/to/cert.pem"

# Path to the private key file or the private key in PEM format.
# Note: DER and PEM format are supported for file.
private_key = "path/to/key.pem"


# Reverse proxies configuration.
# Note: Multiple proxies are supported.
[[proxies]]

# Allow ports.
# Note: If you want to allow all ports, you can set it to { start = 1, end = 65535 }.
# See more details in full exmaple configuration.
allow_ports = { start = 1, end = 63335 }

# Users configuration.
# Format: <uuid> = "<password>"
# Note: UUID must be unique in all proxies.
# You can use `asport-server uuid` command to generate a UUID.
# The example UUID and password are only examples. You MUST replace them with your own UUID and password.
[proxies.users]
00000000-0000-0000-0000-000000000000 = "password"
00000000-0000-0000-0000-000000000001 = "password"